### ISSUE TITLE
Updating failed. Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by itskieranuk** [Automattic/fb-instant-articles#1075] opened 2021-03-17 00:16 UTC
## Steps required to reproduce the problem

1.  Update article post without using classic editor
2. When updating, a response will show Updating failed. Unexpected token < in JSON at position 0
3. Although the article has updated
4. If you update a post in the old classic editor, you do not get this error which suggests its WordPress new editor causing this issue.

## Actual Result 
IUpdating failed. Unexpected token < in JSON at position 0

## Version Info

4.2.1 for the plugin
Wordpress 5.6.2
PHP 7.4

Any ideas on how to prevent this popup? As we'd prefer to use the new editor in WordPress and not classic.

**Comment by kierandevuk** [comment] 2021-03-17 00:19
It seems this issue has never been fixed with #1009 - Disappointing the developers have not bothered.

**Comment by gthayer** [comment] 2022-02-25 21:08
Having the same issues. In my case, the cause is a response from Facebook saying the application has not yet been authorized.

The plugin appears to be printing the warning from facebook inside of the JSON response sent after updating the post. 

Setting `define( 'WP_DEBUG', false );` or `error_reporting( null );` is not enough to suppress the warning message.

**Comment by gthayer** [comment] 2022-02-25 21:27
I believe the offending lines are here:

https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L522-L523

**Comment by GaryJones** [comment] 2022-10-16 02:32
That code seems odd - there's no `</pre>` for instance, and random output from a graph call doesn't seem logical in that context. The code has been removed in https://github.com/Automattic/fb-instant-articles/commit/6275d09a6861169ac23d7d6d4a473c868579925b.

**Closed by GaryJones** 2022-10-16 02:32 UTC
Labels: type: bug, status: needs investigation
